# Generated by Django 3.2.9 on 2021-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
