# Generated by Django 3.2.9 on 2021-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='shortDesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
