# Generated by Django 3.2.9 on 2021-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20211124_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateField(),
        ),
    ]
