# Generated by Django 3.2.9 on 2021-11-24 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_testdrive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 15, 47, 30, 456961, tzinfo=utc)),
        ),
    ]
