# Generated by Django 3.2.9 on 2021-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_enquiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiry'},
        ),
        migrations.AlterModelOptions(
            name='testdrive',
            options={'verbose_name_plural': 'Test Drive'},
        ),
        migrations.AddField(
            model_name='cars',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
