# Generated by Django 3.2.9 on 2021-11-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carsimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsimage',
            options={'verbose_name_plural': 'Cars Images'},
        ),
    ]
