# Generated by Django 3.2.9 on 2021-11-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_carsimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsimage',
            name='name',
            field=models.CharField(blank=True, default='Car', max_length=100, null=True),
        ),
    ]
