# Generated by Django 3.2.9 on 2021-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_carsimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
