# Generated by Django 3.2.9 on 2021-11-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carsimage_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsimage',
            name='featured',
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
