# Generated by Django 3.2.9 on 2021-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20211126_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
