# Generated by Django 3.2.9 on 2021-12-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_carsimage_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
