# Generated by Django 3.2.9 on 2021-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
